# start from the trestletech/plumber image
FROM trestletech/plumber:latest as builder

LABEL maintainer="Lakshya Tyagi"

# install the linux libraries needed for plumber
RUN apt-get update -qq && apt-get install -y \
  libssl-dev \
  libcurl4-gnutls-dev \
  libcurl4-gnutls-dev \
  libcairo2-dev \
  libxt-dev \
  libssh2-1-dev \
  libsodium-dev \
  libsasl2-dev

# system library dependency for the app
RUN apt-get update && apt-get install -y \
    libmpfr-dev


# install packages
RUN R -e "install.packages('plumber')"
RUN R -e "install.packages('DBI', repos='https://cloud.r-project.org/')"
RUN R -e "install.packages('RJDBC', repos='https://cloud.r-project.org/')"
RUN R -e "install.packages('promises', repos='https://cloud.r-project.org/')"
RUN R -e "install.packages('jsonlite', repos='https://cloud.r-project.org/')"
RUN R -e "install.packages('sodium', repos='https://cloud.r-project.org/')"
RUN R -e "install.packages('dplyr', repos='https://cloud.r-project.org/')"
RUN R -e "install.packages('lubridate', repos='https://cloud.r-project.org/')"
RUN R -e "install.packages('openssl', repos='https://cloud.r-project.org/')"
RUN R -e "install.packages('mongolite', repos='https://cloud.r-project.org/')"
RUN R -e "install.packages('jose', repos='https://cloud.r-project.org/')"

# copy everything from the current directory into the container
COPY / /


EXPOSE 3005

# when the container starts, start the plumber.R script
ENTRYPOINT ["Rscript", "plumber.R"]
